PracticaHotel1/HotelSayula/urls.py
from django.urls import path
from django.conf.urls import url, handler404, handler500
from django.contrib.auth.decorators import login_required
from .views import index,check,respaldo,backup
from .views import ClienteList, ClienteCreate, ClienteUpdate, ClienteDelete
from .views import PaiList, PaiCreate, PaiUpdate, PaiDelete
from .views import CiudadeList, CiudadeCreate, CiudadeUpdate, CiudadeDelete
from .views import EstadoList, EstadoCreate, EstadoUpdate, EstadoDelete
from .views import ReservacioneList, ReservacioneCreate, ReservacioneUpdate, ReservacioneDelete
from .views import HabitacioneList, HabitacioneCreate, HabitacioneUpdate, HabitacioneDelete
from .views import RecepcionistaList, RecepcionistaCreate, RecepcionistaUpdate, RecepcionistaDelete


urlpatterns = [
    path('',login_required(index)),
    path('respalda', backup, name='backup'),
    path('check', check, name='check'),
    path('respaldo',login_required(respaldo)),
    path('añadir_cliente',login_required(ClienteCreate.as_view())),
    path('consultar_cliente',login_required(ClienteList.as_view()),name='ver_cliente'),
    url(r'^modificar_cliente/(?P<pk>\d+)/$',login_required(ClienteUpdate.as_view()), name= 'modi_cliente'),
    url(r'^eliminar_cliente/(?P<pk>\d+)/$',login_required(ClienteDelete.as_view()), name= 'eli_cliente'),
    path('consultar_pai',login_required(PaiList.as_view()),name='ver_pai'),
    path('añadir_pai',login_required(PaiCreate.as_view())),
    url(r'^modificar_pai/(?P<pk>\d+)/$',login_required(PaiUpdate.as_view()), name= 'modi_pai'),
    url(r'^eliminar_pai/(?P<pk>\d+)/$',login_required(PaiDelete.as_view()), name= 'eli_pai'),
    path('consultar_estado',login_required(EstadoList.as_view()),name='ver_estado'),
    path('añadir_estado',login_required(EstadoCreate.as_view())),
    url(r'^modificar_estado/(?P<pk>\d+)/$',login_required(EstadoUpdate.as_view()), name= 'modi_estado'),
    url(r'^eliminar_estado/(?P<pk>\d+)/$',login_required(EstadoDelete.as_view()), name= 'eli_estado'),
    path('consultar_ciudade',login_required(CiudadeList.as_view()),name='ver_ciudade'),
    path('añadir_ciudade',login_required(CiudadeCreate.as_view())),
    url(r'^modificar_ciudade/(?P<pk>\d+)/$',login_required(CiudadeUpdate.as_view()), name= 'modi_ciudade'),
    url(r'^eliminar_ciudade/(?P<pk>\d+)/$',login_required(CiudadeDelete.as_view()), name= 'eli_ciudade'),
    path('consultar_recepcionista',login_required(RecepcionistaList.as_view()),name='ver_recepcionista'),
    path('añadir_recepcionista',login_required(RecepcionistaCreate.as_view())),
    url(r'^modificar_recepcionista/(?P<pk>\d+)/$',login_required(RecepcionistaUpdate.as_view()), name= 'modi_recepcionista'),
    url(r'^eliminar_recepcionista/(?P<pk>\d+)/$',login_required(RecepcionistaDelete.as_view()), name= 'eli_recepcionista'),
    path('consultar_reservacione',login_required(ReservacioneList.as_view()),name='ver_reservacione'),
    path('añadir_reservacione',login_required(ReservacioneCreate.as_view())),
    url(r'^modificar_reservacione/(?P<pk>\d+)/$',login_required(ReservacioneUpdate.as_view()), name= 'modi_reservacione'),
    url(r'^eliminar_reservacione/(?P<pk>\d+)/$',login_required(ReservacioneDelete.as_view()), name= 'eli_reservacione'),
    path('consultar_habitacione',login_required(HabitacioneList.as_view()),name='ver_habitacione'),
    path('añadir_habitacione',login_required(HabitacioneCreate.as_view())),
    url(r'^modificar_habitacione/(?P<pk>\d+)/$',login_required(HabitacioneUpdate.as_view()), name= 'modi_habitacione'),
    url(r'^eliminar_habitacione/(?P<pk>\d+)/$',login_required(HabitacioneDelete.as_view()), name= 'eli_habitacione'),

]

PracticaHotel1/PracticaHotel/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth.views import LoginView
from django.contrib.auth.views import logout_then_login
from django.contrib.auth import views as auth_views
from HotelSayula.views import RegistrarUsuario


urlpatterns = [
    path('admin/', admin.site.urls),
    path('index/', include ('HotelSayula.urls',namespace=None)),
    path('accounts/login/', LoginView.as_view(template_name='HotelSayula/login.html'), name="login"),
    path('logout',logout_then_login,name='logout'),
    path('crear_usuario',RegistrarUsuario.as_view()),
    path('api-auth/', include('rest_framework.urls')),
]

PracticaHotel1/HotelSayula/models.py
from django.db import models
# Create your models here.
class Cliente(models.Model):
    Id_Cliente = models.IntegerField(db_column='Id_Cliente', primary_key=True)  # Field name made lowercase.
    NombreC = models.CharField(db_column='NombC', max_length=30, blank=True, null=True)  # Field name made lowercase.
    AP_C = models.CharField(db_column='AP_C', max_length=30, blank=True, null=True)  # Field name made lowercase.
    AM_M = models.CharField(db_column='AM_M', max_length=30, blank=True, null=True)  # Field name made lowercase.
    TCel_C = models.IntegerField(db_column='TCel_C',blank=True, null=True)  # Field name made lowercase.
    TCasa_C = models.IntegerField(db_column='TCasa_C', blank=True, null=True)  # Field name made lowercase.
    Cantidad_Personas = models.IntegerField(db_column='Cantidad de personas', blank=True, null=True)  # Field name made lowercase.
    Ciudad=models.CharField(db_column='Ciudad', max_length=15, blank=True, null=True)
    Estado=models.CharField(db_column='Estado', max_length=15, blank=True, null=True)
    Pais=models.CharField(db_column='Pais', max_length=15, blank=True, null=True)
    Numero_Habitaciones=models.IntegerField(db_column='Numero_Habitaciones', blank=True, null=True)  
    class meta:
        managed = False
        db_table = 'clientes'

class Ciudade(models.Model):
    Id_Ciudad = models.IntegerField(db_column='Id_Ciudad', primary_key=True)  # Field name made lowercase.
    Nombre_C = models.CharField(db_column='Nomb_C', max_length=15, blank=True, null=True)  # Field name made lowercase.
    class meta:
        managed = False
        db_table = 'ciudad'
class Estado(models.Model):
    Id_Estado= models.IntegerField(db_column='Id_Ciudad', primary_key=True)  # Field name made lowercase.
    Nombre_E = models.CharField(db_column='Nomb_E', max_length=15, blank=True, null=True)  # Field name made lowercase.
    class meta:
        managed = False
        db_table = 'estado'
class Pai(models.Model):
    Id_Pais = models.IntegerField(db_column='Id_Ciudad', primary_key=True)  # Field name made lowercase.
    Nombre_P = models.CharField(db_column='Nomb_C', max_length=15, blank=True, null=True)  # Field name made lowercase.
    class meta:
        managed = False
        db_table = 'pais'
class Habitacione(models.Model):
    Numero_Habitaciones = models.IntegerField(db_column='Numero_Habitaciones', primary_key=True)  # Field name made lowercase.
    Precio= models.FloatField(db_column='NombC',blank=True, null=True)  # Field name made lowercase.
    Disponibilidad = models.BooleanField(db_column='AP_C',  blank=True, null=True)  # Field name made lowercase.
    Tipo = models.CharField(db_column='AM_M', max_length=30, blank=True, null=True)  # Field name made lowercase.
    Descripcion = models.CharField(db_column='Sexo', max_length=100, blank=True, null=True)  # Field name made lowercase.
    class meta:
        managed = False
        db_table = 'habitaciones'
class Reservacione(models.Model):
    Id_Reservacion = models.IntegerField(db_column='Id_Reservacion', primary_key=True)  # Field name made lowercase.
    Fecha_Reservacion= models.DateField(db_column='Fecha_Reservacion',  blank=True, null=True)  # Field name made lowercase.
    Fecha_Entrada = models.DateField(db_column='Fecha_Entrada', blank=True, null=True)  # Field name made lowercase.
    Fecha_Salida = models.DateField(db_column='Fecha_Salida',blank=True, null=True)  # Field name made lowercase.
    Total = models.FloatField(db_column='Total',  blank=True, null=True)
    Subtotal=models.FloatField(db_column='Subtotal', blank=True, null=True)
    class meta:
        managed = False
        db_table = 'reservaciones'
class Recepcionista(models.Model):
    Id_Empleado = models.IntegerField(db_column='Id_Empleado', primary_key=True)  # Field name made lowercase.
    Nombre_R = models.CharField(db_column='Nombre_R', max_length=30, blank=True, null=True)  # Field name made lowercase.
    AP_R = models.CharField(db_column='AP_C', max_length=30, blank=True, null=True)  # Field name made lowercase.
    AM_R = models.CharField(db_column='AM_M', max_length=30, blank=True, null=True)  # Field name made lowercase.
    Turno = models.CharField(db_column='Sexo', max_length=30, blank=True, null=True)  # Field name made lowercase.
    class meta:
        managed = False
        db_table = 'recepcionistas'

PracticaHotel1/HotelSayula/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Cliente,Pai,Estado,Ciudade,Reservacione,Recepcionista,Habitacione

class Registroform(UserCreationForm):
    
    class Meta:
        model = User
        fields = [
            'username',
            'first_name',
            'last_name',
            'email',
        ]
        labels = {
            'username' : 'Nombre de usuario',
            'first_name' : 'Nombre de pila',
            'last_name' : 'Apellidos',
            'email' : 'Correo electronico',
        }

class Ciudadeform(forms.ModelForm):
    class Meta:
        model = Ciudade
        fields = [
            'Id_Ciudad',
            'Nombre_C',
        ]
        labels = {
            'Id_Ciudad' : 'Id_Ciudad',
            'Nombre_C' : 'Nombre_C',
        }
        widgets = {
            'Id_Ciudad' : forms.TextInput(attrs={'class':'form-control'}),
            'Nombre_C' : forms.TextInput(attrs={'class':'form-control'}),
        
        }
class Paiform(forms.ModelForm):
    class Meta:
        model = Pai
        fields = [
            'Id_Pais',
            'Nombre_P',
        ]
        labels = {
            'Id_Pais' : 'Id_Pais',
            'Nombre_P' : 'Nombre_P',
        }
        widgets = {
            'Id_Pais' : forms.TextInput(attrs={'class':'form-control'}),
            'Nombre_P' :forms.TextInput(attrs={'class':'form-control'}),
        }

class Habitacioneform(forms.ModelForm):
    class Meta:
        model = Habitacione
        fields = [
            'Numero_Habitaciones',
            'Precio',
            'Disponibilidad',
            'Tipo',
            'Descripcion',
        ]
        labels = {
            'Numero_Habitaciones' : 'Numero_Habitaciones',
            'Precio' : 'Precio',
            'Disponibilidad' : 'Disponibilidad',
            'Tipo' : 'Tipo',
            'Descripcion' : 'Descripcion',
        }
        widgets = {
            'Numero_Habitaciones' : forms.TextInput(attrs={'class':'form-control'}),
            'Precio' : forms.TextInput(attrs={'class':'form-control'}),
            'Disponibilidad' : forms.TextInput(attrs={'class':'form-control'}),
            'Tipo' : forms.TextInput(attrs={'class':'form-control'}),
            'Descripcion' : forms.TextInput(attrs={'class':'form-control'}),
        }

class Recepcionistaform(forms.ModelForm):
    class Meta:
        model = Recepcionista
        fields = [
            'Id_Empleado',
            'Nombre_R',
            'AP_R',
            'AM_R',
            'Turno',
        ]
        labels = {
            'Id_Empleado' : 'Id_Empleado',
            'Nombre_R' : 'Nombre_R',
            'AP_R' : 'AP_R',
            'AM_R' : 'AM_R',
            'Turno' : 'Turno',


        }
        widgets = {
            'Id_Empleado': forms.TextInput(attrs={'class':'form-control'}),
            'Nombre_R' : forms.TextInput(attrs={'class':'form-control'}),
            'AP_R' : forms.TextInput(attrs={'class':'form-control'}),
            'AM_R' : forms.TextInput(attrs={'class':'form-control'}),
            'Turno': forms.TextInput(attrs={'class':'form-control'}),

        }

class Reservacioneform(forms.ModelForm):
    class Meta:
        model = Reservacione
        fields = [
            'Id_Reservacion',
            'Fecha_Reservacion',
            'Fecha_Entrada',
            'Fecha_Salida',
            'Total',
            'Subtotal',

        ]
        labels = {
            'Id_Reservacion' : 'Id_Reservacion',
            'Fecha_Reservacion' : 'Fecha_Reservacion',
            'Fecha_Entrada' : 'Fecha_Entrada',
            'Fecha_Salida' : 'Fecha_Salida',
            'Total' : 'Total',
            'Subtotal' : 'Subtotal',
        }
        widgets = {
            'Id_Reservacion' : forms.TextInput(attrs={'class':'form-control'}),
            'Fecha_Reservacion' : forms.TextInput(attrs={'class':'form-control'}),
            'Fecha_Entrada' : forms.TextInput(attrs={'class':'form-control'}),
            'Fecha_Salida' : forms.TextInput(attrs={'class':'form-control'}),
            'Total' : forms.TextInput(attrs={'class':'form-control'}),
            'Subtotal':forms.TextInput(attrs={'class':'form-control'}), 
        }
class Estadoform(forms.ModelForm):
    class Meta:
        model = Estado
        fields = [
            'Id_Estado',
            'Nombre_E',
        ]
        labels = {
            'Id_Estado' : 'Id_Estado',
            'Nombre_E' : 'Nombre_E',
        }
        widgets = {
            'Id_Estado' : forms.TextInput(attrs={'class':'form-control'}),
            'Nombre_E' : forms.TextInput(attrs={'class':'form-control'}),

        }
class Clienteform(forms.ModelForm):
    class Meta:
        model = Cliente
        fields = [
            'Id_Cliente',
            'NombreC',
            'AP_C',
            'AM_M',
            'TCel_C',
            'TCasa_C',
            'Cantidad_Personas',
            'Ciudad',
            'Estado',
            'Pais',
            'Numero_Habitaciones',
        ]
        labels = {
            'Id_Cliente' : 'Id_Cliente',
            'NombreC'    : 'NombreC',
            'AP_C'       : 'AP_C',
            'AM_M'       : 'AM_M',
            'TCel_C'     :'TCel_C',
            'TCasa_C'    : 'TCasa_C',
            'Cantidad_Personas' : 'Cantidad_Personas',
            'Ciudad'     : 'Ciudad',
            'Estado'     : 'Estado',
            'Pais'       : 'Pais',
            'Numero_Habitaciones' : 'Numero_Habitaciones',
        }
        widgets = {
            'Id_Cliente' : forms.TextInput(attrs={'class':'form-control'}),
            'NombreC' : forms.TextInput(attrs={'class':'form-control'}),
            'AP_C' : forms.TextInput(attrs={'class':'form-control'}),
            'AM_M' : forms.TextInput(attrs={'class':'form-control'}),
            'TCel_C' : forms.TextInput(attrs={'class':'form-control'}),
            'TCasa_C' : forms.TextInput(attrs={'class':'form-control'}),
            'Cantidad_Personas' : forms.TextInput(attrs={'class':'form-control'}),
            'Ciudad' : forms.TextInput(attrs={'class':'form-control'}),
            'Estado' : forms.TextInput(attrs={'class':'form-control'}),
             'Pais' : forms.TextInput(attrs={'class':'form-control'}),
            'Numero_Habitaciones' : forms.TextInput(attrs={'class':'form-control'}),
        }
        
class Registroform(UserCreationForm):
    class Meta:
        model = User
        fields = [
            'username',
            'first_name',
            'last_name',
            'email',
        ]
        labels = {
            'username' : 'Nombre de usuario',
            'first_name' : 'Nombre de pila',
            'last_name' : 'Apellidos',
            'email' : 'Correo electronico',
        }

PracticaHotel1/templates/HotelSayula/añadir_cliente.html
<!DOCTYPE html  {% load static %} >
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="/static/css/darkly.min.css">
    <title>Añadir Cliente</title>
</head>
<body>
        
    <div>
        {% if perms.HotelSayula.add_cliente %}
        <h4><a href="/index">Pagina de inicio</a></h4>
        <form method="POST">
            {% csrf_token %}
            {{form.as_p}}
            <button type="submit">
                Guardar
            </button>
        </form>
        {% else  %}
        <center>
                <h1>No tienes permiso :( </h1>
                <h4><a href="/index">Pagina de inicio</a></h4>
                
        </center>
        
        {% endif %}
            
        </div>
    
</body>
</html>

PracticaHotel1/templates/HotelSayula/añadir_reservacion.html
<!DOCTYPE html  {% load static %} >
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="/static/css/darkly.min.css">
    <title>Añadir Reservacion</title>
</head>
<body>
        
    <div>
        {% if perms.HotelSayula.add_reservacione %}
        <h4><a href="/index">Pagina de inicio</a></h4>
        <form method="POST">
            {% csrf_token %}
            {{form.as_p}} 
            <button type="submit">
                Guardar
            </button>
        </form>
        {% else  %}
        <center>
                <h1>No tienes permiso  </h1>
                <h4><a href="/index">Pagina de inicio</a></h4>
                
        </center>
        
        {% endif %}
            
        </div>
    
</body>
</html>

PracticaHotel1/templates/HotelSayula/consultar_estado.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="/static/css/darkly.min.css">
    <title>Consultar </title>
</head>
<body>
    <h4><a href="/index">Pagina de inicio</a></h4>
    <table class="table table-bordered">
        <thead>
            <tr>
                <td>Id_Estado</td>
                <td>Nombre_E</td>
              
            </tr>
        </thead>
        <tbody>
            {% if object_list %}
            {% for estado in object_list %}
            <tr>
                <td>{{estado.Id_Estado}}</td>
                <td>{{estado.Nombre_E}}</td>
           
                <td>
                    {% if perms.HotelSayula.change_estado %}
                        <a class="btn btn-primary" href="{% url 'modi_estado' estado.Id_Estado %}">Editar</a>
                    {% endif %}
                    {% if perms.HotelSayula.delete_estado %}
                        <a class="btn btn-danger" href="{% url 'eli_estado' estado.Id_Estado %}">Borrar</a>
                    {% endif %}
                            
                </td>
            </tr>
            {% endfor %}

            {% else %}
            <h1>No hay registros</h1>

            {% endif %}
        </tbody>
    </table>
</body>
</html>

PracticaHotel1/templates/HotelSayula/consultar_habitacione.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="/static/css/darkly.min.css">
    <title>Consultar </title>
</head>
<body>
    <h4><a href="/index">Pagina de inicio</a></h4>
    <table class="table table-bordered">
        <thead>
            <tr>
                <td>Numero_Habitaciones</td>
                <td>Precio</td>
                <td>Disponibilidad</td>
                <td>Tipo</td>
                <td>Descripcion</td>
               
            </tr>
        </thead>
        <tbody>
            {% if object_list %}
            {% for habitacione in object_list %}
            <tr>
                <td>{{habitacione.Numero_Habitaciones}}</td>
                <td>{{habitacione.Precio}}</td>
                <td>{{habitacione.Disponibilidad}}</td>
                <td>{{habitacione.Tipo}}</td>
                <td>{{habitacione.Descripcion}}</td>
                <td>
                    {% if perms.HotelSayula.change_habitacione %}
                      <a class="btn btn-primary" href= "{% url 'modi_habitacione' habitacione.Numero_Habitaciones %}">Editar</a>
                    {% endif %}
                    {% if perms.HotelSayula.delete_habitacione %}
                        <a class="btn btn-danger" href="{% url 'eli_habitacione' habitacione.Numero_Habitaciones %}">Borrar</a>
                    {% endif %}
                            
                </td>
            </tr>
            {% endfor %}

            {% else %}
            <h1>No hay registros</h1>

            {% endif %}
        </tbody>
    </table>
</body>
</html>

PracticaHotel1/templates/HotelSayula/consultar_pai.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="/static/css/darkly.min.css">
    <title>Consultar </title>
</head>
<body>
    <h4><a href="/index">Pagina de inicio</a></h4>
    <table class="table table-bordered">
        <thead>
            <tr>
                <td>Id_Pais</td>
                <td>Nombre_P</td>
              
            </tr>
        </thead>
        <tbody>
            {% if object_list %}
            {% for pai in object_list %}
            <tr>
                <td>{{pai.Id_Pais}}</td>
                <td>{{pai.Nombre_P}}</td>
          
                <td>
                    {% if perms.HotelSayula.change_pai %}
                        <a class="btn btn-primary" href="{% url 'modi_pai' pai.Id_Pais %}">Editar</a>
                    {% endif %}
                    {% if perms.HotelSayula.delete_pai %}
                        <a class="btn btn-danger" href="{% url 'eli_pai' pai.Id_Pais %}">Borrar</a>
                    {% endif %}
                            
                </td>
            </tr>
            {% endfor %}

            {% else %}
            <h1>No hay registros</h1>

            {% endif %}
        </tbody>
    </table>
</body>
</html>

PracticaHotel1/templates/HotelSayula/eliminar_ciudade.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="/static/css/darkly.min.css">
    <title>Eliminar </title>
</head>
<body>
    <h4><a href="../index/">Pagina de inicio</a></h4>
    <form method="POST">
        {% csrf_token %}
        <h3>¿Desea eliminar el registro{{ciudade.Id_Ciudad}}?</h3>
        <button class="btn btn-danger" type="submit">
            SI, eliminar
        </button>
        <a class="btn btn-default" href="{% url 'ver_ciudade' %}">Cancelar</a>
    </form>
</body>
</html>

PracticaHotel1/templates/HotelSayula/eliminar_estado.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="/static/css/darkly.min.css">
    <title>Eliminar </title>
</head>
<body>
    <h4><a href="../index/">Pagina de inicio</a></h4>
    <form method="POST">
        {% csrf_token %}
        <h3>¿Desea eliminar el registro{{estado.Id_Estado}}?</h3>
        <button class="btn btn-danger" type="submit">
            SI, eliminar
        </button>
        <a class="btn btn-default" href="{% url 'ver_estado ' %}">Cancelar</a>
    </form>
</body>
</html>

PracticaHotel1/templates/HotelSayula/eliminar_pai.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="/static/css/darkly.min.css">
    <title>Eliminar </title>
</head>
<body>
    <h4><a href="../index/">Pagina de inicio</a></h4>
    <form method="POST">
        {% csrf_token %}
        <h3>¿Desea eliminar el registro{{pai.Id_Pais}}?</h3>
        <button class="btn btn-danger" type="submit">
            SI, eliminar
        </button>
        <a class="btn btn-default" href="{% url 'ver_pai' %}">Cancelar</a>
    </form>
</body>
</html>

PracticaHotel1/templates/HotelSayula/eliminar_recepcionista.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="/static/css/darkly.min.css">
    <title>Eliminar </title>
</head>
<body>
    <h4><a href="../index/">Pagina de inicio</a></h4>
    <form method="POST">
        {% csrf_token %}
        <h3>¿Desea eliminar el registro{{recepcionista.Id_Empleado}}?</h3>
        <button class="btn btn-danger" type="submit">
            SI, eliminar
        </button>
        <a class="btn btn-default" href="{% url 'ver_recepcionista' %}">Cancelar</a>
    </form>
</body>
</html>

PracticaHotel1/templates/HotelSayula/eliminar_reservacione.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="/static/css/darkly.min.css">
    <title>Eliminar 
        
    </title>
</head>
<body>
    <h4><a href="../index/">Pagina de inicio</a></h4>
    <form method="POST">
        {% csrf_token %}
        <h3>¿Desea eliminar el registro{{rerservacione.Id_Reservacion}}?</h3>
        <button class="btn btn-danger" type="submit">
            SI, eliminar
        </button>
        <a class="btn btn-default" href="{% url 'ver_reservacione' %}">Cancelar</a>
    </form>
</body>
</html>

PracticaHotel1/templates/HotelSayula/login.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="/static/css/darkly.min.css">
    <title>Login</title>
</head>

    <form class="box" form method="post">
        {% csrf_token %}
        <div class="row">
            <div class="col-md-6 col-md-offset-3">
            <div class="form-group">
            <label for="username">Nombre de Usuario:</label>
            <input class="form-control" type="text" placeholder="Usuario" name="username">
            </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6 col-md-offset-3">
            <div class="form-group">
            <label for="username">Contraseña:</label>
            <input class="form-control" type="password" placeholder="Contraseña" name="password">
            </div>
            </div>
        </div> 
        <input class="btn btn-primary" type="submit" value='Ingresar'>
                </div>
                </div>
            </div>

    </form>

</html>

PracticaHotel1/templates/HotelSayula/respaldo.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="/static/css/darkly.min.css">
    <title>Respaldo</title>
</head>
<body>
    <br>    
    <br>
    <label style="margin-left:38%;"><h1>Respaldar:</h1></label>
    <br>
    <br>
    <input style="margin-left:40%;" type="text" name="nombredelacaja">
    <br>
    <br>
    <input style="margin-left:44%;" class="btn btn-primary" type="submit">
</body>
</html>